spring:
  datasource:
    url: jdbc:mysql://localhost:3306/techdirectory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: techUser
    password: techpass123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8080

jwt:
  secret: your_super_secret_jwt_key_change_this_in_production_please_make_it_long
  expirationMinutes: 120

cors:
  allowed-origins: http://localhost:5173

management:
  endpoints:
    web:
      exposure:
        include: health,info
